consider python2 before python

diff --git a/eb b/eb
--- a/eb
+++ b/eb
@@ -39,35 +39,39 @@
 # @author: Pieter De Baets (Ghent University)
 # @author: Jens Timmerman (Ghent University)
 
-PYTHON=python
-
 # Python 2.6 or more recent 2.x required
 REQ_MAJ_PYVER=2
 REQ_MIN_PYVER=6
 REQ_PYVER=${REQ_MAJ_PYVER}.${REQ_MIN_PYVER}
 
+PYTHON=python$REQ_MAJ_PYVER
+which $PYTHON &> /dev/null
+if [ $? -ne 0 ]
+then
+    PYTHON=python
+    which $PYTHON &> /dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR: $PYTHON not available in \$PATH?"
+        exit 1
+    fi
+fi
+
 # make sure Python version being used is compatible
 pyver=`$PYTHON -V 2>&1 | cut -f2 -d' '`
 pyver_maj=`echo $pyver | cut -f1 -d'.'`
-
-if [ $pyver_maj -ne $REQ_MAJ_PYVER ]
-then
-    PYTHON=${PYTHON}$REQ_MAJ_PYVER}
-    pyver=`$PYTHON -V 2>&1 | cut -f2 -d' '`
-    pyver_maj=`echo $pyver | cut -f1 -d'.'`
-fi
+pyver_min=`echo $pyver | cut -f2 -d'.'`
 
 if [ $pyver_maj -ne $REQ_MAJ_PYVER ]
 then
     echo "ERROR: EasyBuild is currently only compatible with Python v${REQ_MAJ_PYVER}.x, found v${pyver}" 1>&2
-    exit 1
+    exit 2
 fi
 
-pyver_min=`echo $pyver | cut -f2 -d'.'`
 if [ $pyver_min -lt $REQ_MIN_PYVER ]
 then
     echo "ERROR: EasyBuild requires Python v${REQ_PYVER} or a more recent v${REQ_MAJ_PYVER}.x, found v${pyver}." 1>&2
-    exit 2
+    exit 3
 fi
 
 $PYTHON -m easybuild.main $@
